OUTPUT_ARCH(riscv)
ENTRY(_start)

MEMORY {
    RAM    : org = 0x0000000080200000, len = 8M
    VDSO   : org = 0x00007f0000000000, len = 4K
    KBSS   : org = 0xffffffff40000000, len = 2M
    KIMAGE : org = 0xffffffff80200000, len = 8M
}

REGION_ALIAS("REGION_TEXT", KIMAGE);
REGION_ALIAS("REGION_RODATA", KIMAGE);
REGION_ALIAS("REGION_DATA", KIMAGE);
REGION_ALIAS("REGION_BSS", KBSS);

REGION_ALIAS("LINK_REGION_TEXT", RAM);
REGION_ALIAS("LINK_REGION_RODATA", RAM);
REGION_ALIAS("LINK_REGION_DATA", RAM);
REGION_ALIAS("LINK_REGION_BSS", RAM);

_stext = ORIGIN(REGION_TEXT) + LOADADDR(.text) - ORIGIN(RAM);
